import React from 'react';
import './globals.scss';
import { Manrope } from 'next/font/google';
import { cn } from '@/shared/ui/utils';
import { AppProvider } from '@/app/_providers/app-provider';

export const metadata = {
  title: 'Jazzo Studio',
  description: 'Generated by create next app'
};

const manrope = Manrope({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
      className={cn(
        'min-h-screen bg-background wrapper',
        manrope.className
      )}
    >
    <AppProvider>
      {children}
    </AppProvider>
    </body>
    </html>
  );
}
